version: '3.9'

services:
  influxdb:
    image: influxdb:latest
    hostname: influxdb
    env_file: variables.env
    networks:
      back:
        aliases:
          - database

  fastapi:
    build:
      context: ./pyflux
      dockerfile: Dockerfile
    hostname: fastapi
    env_file: variables.env
    ports:
      - 3000:5000/tcp
    networks:
      front:
      back:

networks:
  front:
  back:
